sudo: required
services:
  - docker

before_install:
  - docker build -t sakipgur/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sakipgur/react-test npm test -- --coverage

after_success:
  - docker build -t sakipgur/multi-client ./client
  - docker build -t sakipgur/multi-nginx ./nginx
  - docker build -t sakipgur/multi-server ./server
  - docker build -t sakipgur/multi-worker ./worker
  # Log in to the docker CLI, we will use travis for encypted credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sakipgur/multi-client
  - docker push sakipgur/multi-nginx
  - docker push sakipgur/multi-server
  - docker push sakipgur/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-112569602180
  bucker_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY